### ISSUE TITLE
`gulp` コマンドでエラー

### ISSUE THREAD

**Issue by koya-iwasaki** [noliaki/new-site#1]
```
λ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-rimraf'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\koya.iwasaki\Documents\new-site\gulpfile.js:12:24
    at Object.<anonymous> (C:\Users\koya.iwasaki\Documents\new-site\gulpfile.js:132:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
@noliaki `gulp-rimraf` じゃなくて `rimraf` ？ `rimraf` にしても clean で引っかかる。
（初めてのIssueカキコ）

**Comment by noliaki** [comment]
@koya-iwasaki プラグインを'gulp-rimraf'から'rimraf'に変更してみた。
http://qiita.com/shinnn/items/bd7ad79526eff37cebd0

**Comment by noliaki** [comment]
@koya-iwasaki 菊池くんがwinでも出来たって言うから閉じます。
